### ISSUE TITLE
News series listing could be added

### ISSUE THREAD

**Issue by minusQuantumNeko** [ppy/osu-wiki#11253]
Currently it's quite hard to find newsposts from specific series, and there is a list only for osu!monthly right now, so it would be nice to have something like this.

**Comment by Walavouchey** [comment]
thinking of a structure like this

```markdown
# News series

blah blah

## Listing

### Series one

explainer paragraph or two

| Title | Publication date |
| :-- | :-- |

## Series two

explainer paragraph or two

| Title | Publication date |
| :-- | :-- |
```

and a new yaml tag in applicable news posts like so

```yaml
---
layout: post
title: Series one episode one
series_title: Series one
date: 2017-08-17 03:00:00 +0000
---
```

which would allow for easy automation
