### ISSUE TITLE
Specify wiki front page description file format

### ISSUE THREAD

**Issue by LiquidPL** [ppy/osu-wiki#1209]
As I've been discussing with people on #osu-wiki (long time ago :C), I'd like to get on with implementing the front page on web side. First however, I'd like to ask you to describe exactly how do you want the structure of its *.yaml* file to look like.

**Comment by TPGPL** [comment]
i suggest something like
![](https://puu.sh/zWjS0/3e277cb929.png)

but it might need further discussion tho

**Comment by MegaApplePi** [comment]
In a file called `osu-wiki/wiki/Main_Page/en.yaml`:
```yaml
"Online Editing and Ranking":
- "[Forums](/wiki/Forums)"
- "[Submission](/wiki/Submission)"
- "[Beatmap Approval](/wiki/Beatmap_Approval)"
- "[Modding](/wiki/Modding)"
- "[Ranking Criteria](/wiki/Ranking_Criteria)":
  - "[osu!standard](/wiki/Ranking_Criteria/osu!standard)"
  - "[osu!taiko](/wiki/Ranking_Criteria/osu!taiko)"
  - "[osu!catch](/wiki/Ranking_Criteria/osu!catch)"
  - "[osu!mania](/wiki/Ranking_Criteria/osu!mania)"
"World of osu!":
- "[Glossary](/wiki/Glossary)"
- "[Modding](/wiki/Modding)"
- "[Beatmapping](/wiki/Beatmapping)"
- "[Tournaments](/wiki/Tournaments)"
- "[Skinning](/wiki/Skinning)"
"People":
- "[The Team](/wiki/The_Team)"
- "[Global Moderation Team](/wiki/Global_Moderation_Team)"
- "[Language Moderators](/wiki/Language_Moderators)"
- "[Quality Assurance Team](/wiki/Quality_Assurance_Team)"
- "[Beatmap Nominators](/wiki/Beatmap_Nominators)"
- "[osu! Alumni](/wiki/osu!_Alumni)"
- "[Support Team](/wiki/Support_Team)"
```

That was my thought on how it should be structured.

- No item will ever go beyond one level of indentation, but if it does, it should be ignored.
- The group keys (in this example: "People", "World of osu!", and "Online Editing and Ranking") will never have links or images. (For how we would handle heading names that are the same as article titles, we would, for example, have a heading called `"Beatmapping"` then the first item will be `- "[Basic explanation](/wiki/Beatmapping)"`.)
- Markdown is used for translating link text (and the separate files for heading text and allowing for other localised Main Pages).
  - For example, French's main page will be `osu-wiki/wiki/Main_Page/fr.md` and it would basically have the same thing as the `osu-wiki/wiki/Main_Page/en.md` one, but with the link and heading text in French.
- The heading banner text :point_down: will be handled by osu-web.
![image](https://user-images.githubusercontent.com/14264992/38339795-c05667a2-3835-11e8-8bc5-fb9cff9c629f.png)
